name: Install Terrascan
on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
           pip install terrascan
           terrascan
          
