name: Install Terrascan
on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
           ./.github/script.sh
           echo $REBUILD
           echo "------------"
      - name: test
        run: |
           echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
           echo $GITHUB_SHA_SHORT
           echo $REBUILD
          
